version: '3'

services:
  postgres_db:
    container_name: postgres_db
    image: postgres:alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=@sd123
      - POSTGRES_USER=sa
      - POSTGRES_DB=fluentapi_test

volumes:
  postgres_volume:
    driver: local